# Generated by Django 4.0.4 on 2022-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=255555, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, db_index=True, verbose_name='Контент')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фотки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликованно')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Просмотры')),
            ],
        ),
    ]
